- name: Create folder for repo Github
  command: mkdir "{{ name_of_folder_repo_github }}"
  become_user: "{{ vm_user }}"

- name: Change permissions on path_clone_project_in_vm
  become: yes
  become_user: "{{ vm_user }}"
  command: chmod u+w "{{ path_clone_project_in_vm }}"

- name: Clone GitHub project
  git:
    repo: "{{ path_repo_github }}"
    dest: "{{ path_clone_project_in_vm }}"
  become_user: "{{ vm_user }}"
  environment:
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

- name: Change directory to project path with docker-compose is in root project
  shell: |
    cd "{{ path_clone_project_in_vm }}"
  become_user: "{{ vm_user }}"

- name: Add ansible user to the Docker group
  user:
    name: "{{ vm_user }}"
    groups: docker
  become: yes

- name: Copy .env file to project directory
  copy:
    src: "{{ path_env }}"
    dest: "{{ path_clone_project_in_vm }}/.env"
  become_user: "{{ vm_user }}"

- name: Start Docker Compose services
  command: sudo docker-compose -f {{ path_clone_project_in_vm_with_docker_compose_yml }} up -d
  become_user: "{{ vm_user }}"
