name: Mise en production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Remplacer les valeurs dans inventory.ini
        run: |
          sed -i 's#address_ip#94.23.63.215#g' ansible/inventory/inventory.ini
          sed -i 's#user_vm#debian#g' ansible/inventory/inventory.ini
          sed -i 's#ansible_ssh_pass#epitech123#g' ansible/inventory/inventory.ini

      - name: Remplacer les valeurs dans vars_mep.yml
        run: |
          sed -i 's#user_in_vm#debian#g' ansible/vars/vars_mep.yml
          sed -i 's#path_project_in_folder#/home/debian/T-CLO-901-TLS_5#g' ansible/vars/vars_mep.yml
          sed -i 's#repo_github_url#git@github.com:EpitechMscProPromo2024/T-CLO-901-TLS_5.git#g' ansible/vars/vars_mep.yml

      - name: Configurer la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 94.23.63.215 >> ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /dev/null

      - name: mep
        run: ansible-playbook -i ansible/inventory/inventory.ini ansible/main_installation.yml --tags mep
